name: Slack Notification
on: push
jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Slack
        if: always()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: |
            ${{ job.status }} - ${{ github.repository }} - ${{ github.ref }}
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
